#!/bin/sh

for k in 5 10 20 40 60 
do 
 for p in 0 .05 .1 .15 
  do
    for s in 1.3 2
    do
      for r in 0 0.5 0.9
      do
      Rscript simulate_all.R 500 500 $k $p $s $r &


      done 

    done

  done  

done
